apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-app-deploy
spec:
  replicas: 2  # Inicia com 2 pods (1 por worker)
  selector:
    matchLabels:
      app: minha-app
  template:
    metadata:
      labels:
        app: minha-app
    spec:
      containers:
      - name: minha-app
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "200m"
          limits:
            cpu: "500m"
